= Artifical Intelligence(인공지능)의 역사

* 컴퓨터에서 음성 및 작성된 언어를 확인, 이해, 번역하고 데이터를 분석하여 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있게 하는 일련의 기술
* Alan Turing의 1950년에 쓴 논문 'Computing Machinery and Intelligence(계산 기계와 지능)'에서 기계가 사고할 수 있는지 여부를 고찰
** 인공 지능이라는 용어를 처음 만들어 이론적, 철학적 개념으로 제시
---

== 1940년 ~ 1980년

1943년 Warren McCulloch과 Walter Pitts는 인공 뉴런 모델을 제안하여 AI의 핵심 기술인 신경망의 토대를 마련했습니다.

그 뒤를 이어 1950년 Alan Turing은 기계 지능을 평가하기 위한 튜링 테스트의 개념을 소개하는 'Computing Machinery and Intelligence(계산 기계와 지능)'을 출간했습니다.

이를 계기로 대학원생인 Marvin Minsky와 Dean Edmonds는 최초의 신경망 기계인 SNARC를 구축했고, Frank Rosenblatt은 신경망의 초기 모델 중 하나인 Perceptron을 개발했으며, Joseph Weizenbaum은 1951년부터 1969년까지 Rogerian 심리치료사를 시뮬레이션한 최초의 챗봇 중 하나인 ELIZA를 개발했습니다.

1969년부터 1979년까지 Marvin Minsky는 신경망의 한계를 입증했고, 이로 인해 신경망 연구가 일시적으로 쇠퇴했습니다. 첫 번째 'AI 겨울'은 자금 부족과 하드웨어 및 컴퓨팅의 한계로 인해 발생했습니다.

== 1980년 ~ 2006년

1980년대에는 주로 번역과 전사 분야에서 AI 연구에 대한 새로운 관심과 정부 자금이 쏟아졌고, 이 시기에는 의학 등 특정 분야에서 인간의 의사 결정 과정을 시뮬레이션하는 MYCIN과 같은 전문가 시스템이 인기를 얻었습니다. 1980년대 신경망이 부활하면서 David Rumelhart와 John Hopfield는 컴퓨터가 경험을 통해 학습할 수 있다는 것을 보여주는 딥 러닝 기술에 관한 논문을 발표했습니다.

1987년에서 1997년 사이에는 다른 사회경제적 요인과 닷컴 붐으로 인해 두 번째 AI 겨울이 찾아왔습니다. AI 연구는 더욱 세분화되어 다양한 사용 사례에서 분야별 문제를 해결하는 팀들이 생겨났습니다.

1997년부터 2006년경까지 IBM의 Deep Blue 체스 소프트웨어가 세계 체스 챔피언인 Garry Kasparov를 물리치는 등 AI 분야에서 상당한 성과를 거두었습니다. 이 외에도 Judea Pearl은 AI 연구에 확률과 의사 결정 이론을 포함하는 책을 출판했으며 Geoffrey Hinton 등은 딥 러닝을 대중화하여 신경망의 부활을 이끌었습니다. 그러나 상업적 관심은 여전히 제한적이었습니다.

== 2007년 ~

2007년부터 2018년까지 클라우드 컴퓨팅의 발전으로 컴퓨팅 성능과 AI 인프라에 더 쉽게 접근할 수 있게 되었습니다. 이는 기계 학습의 채택 증가, 혁신 및 발전으로 이어졌습니다. Alex Krizhevsky, Ilya Sutskever, Geoffrey Hinton이 개발한 AlexNet이라는 합성곱 신경망(CNN) 아키텍처가 ImageNet 대회에서 우승하여 이미지 인식 분야에서 딥 러닝의 힘을 보여주었고, Google의 AlphaZero는 사람의 데이터 없이 자가 플레이에 의존하여 체스, 장기, 바둑 게임을 마스터했습니다.

2022년에는 인공 지능(AI)과 자연어 처리(NLP)를 사용해 인간과 같은 대화를 나누고 작업을 완료하는 챗봇(예: OpenAI의 ChatGPT)이 대화 능력으로 널리 알려지면서 AI에 대한 관심과 개발이 다시 활발해졌습니다.