= 머신 러닝의 학습 방법

* Supervised Learning (지도 학습)
** 입력 값과 함께 결과 값(정답 레이블)을 같이 주고 학습을 시키는 방법
** 정답을 기반으로 오류를 줄여서 학습하는 방법 즉, 반복 학습을 통해 오류를 줄여가면서 점차 정답에 가까워지는 방법
* Unsupervized Learning (비지도 학습)
** 지도 학습과 달리 정답을 알려주지 않고 예측하는 방법
** 정답을 모르더라도 유사한 것들과 서로 다른 것들을 구분해서 군집을 만들 수 있는 학습 방법
* Semi-supervized Learning (준지도 학습)
** 지도 학습과 비지도 학습을 섞어서 정답을 유추함
** 군집을 학습한 후에, 일부 데이터만 사람이 정답을 매겨주면 그 군집 전체를 사람이 매긴 정답으로 볼 수 있는 원리
* Reinforcement Learning (강화 학습)
* 보상과 벌칙과 한께 여러 번의 시행착오를 거쳐 스스로 학습하는 방법
---

인지과학 분야에서 사람의 학습을 몇 가지로 구분하는데, 머신 러닝에서도 이런 방법론을 적용하여 크게 네 가지 학습 방법으로 구분해서 이야기합니다. 

== Supervised Learning (지도 학습)

네 가지 머신 러닝모델 중 첫 번째는 지도형 학습입니다. 지도형 학습 알고리즘에서는 예시를 통해 머신을 학습합니다. 지도형 학습 모델은 '입력', '출력' 데이터 쌍으로 구성되며, 원하는 값으로 출력 레이블을 지정할 수 있습니다. 예를 들어 머신을 데이지꽃과 팬지꽃의 차이를 식별할 수 있도록 학습습하려고 합니다. 하나의 이진 입력 데이터 쌍에는 데이지꽃의 이미지와 팬지꽃의 이미지가 모두 포함됩니다. 해당 특정 쌍에 원하는 결과는 데이지꽃을 선택하는 것이기 때문에, 이것이 올바른 결과로서 사전 식별됩니다.

시스템은 알고리즘을 통해 시간에 따라 이 학습습 데이터를 모두 컴파일한 다음 상관관계가 있는 유사성, 차이점, 기타 논리 지점을 결정하기 시작하며, 이 작업은 데이지꽃인지 팬지꽃인지 묻는 질문에 대한 답을 스스로 예측할 수 있을 때까지 계속됩니다. 이는 어린 아이에게 일련의 문제를 정답 키와 함께 준 다음, 그들이 한 작업을 보여주고 논리를 설명하도록 하는 것과 같습니다. 지도형 학습 모델은 제품 추천 엔진이나 교통량 분석 앱(예: 하루 중 다른 시간대에 가장 빠른 이동 경로를 예측하는 Waze) 등 일상생활의 다양한 분야에서 사용됩니다.

* 분류(Classification) 알고리즘 +
데이터가 범주형 변수를 예측하기 위해 사용될 때 
이미지에 강아지나 고양이와 같은 레이블을 할당하는 경우에 해당
** 이진 분류(Binary Classification) : 레이블이 두 개인 경우
** 다중 클래스 분류(Multi-Class Classification) : 범주가 두 개 이상인 경우
* 회귀(Regression) 알고리즘
** 연속 값을 예측할 때
** 트레이닝 데이터를 이용하여 연속적인 값을 예측하는 것

== Unsupervized Learning (비지도 학습)

비지도 학습 모델에는 정답 키가 없습니다. 머신이 입력 데이터(대부분 레이블이 없는 비정형 데이터)를 학습한 다음 관련성이 있고 액세스 가능한 데이터를 모두 사용해 패턴과 상관관계를 인식하기 시작합니다. 비지도 학습은 사람이 세상을 관찰하는 방식을 기반으로 다양하게 모델링됩니다. 사람은 직관과 경험에 의존해 사물을 그룹화합니다. 어떤 사물에 대해 경험하는 예시의 수가 많을수록 그것을 분류하고 인식하는 능력이 더욱더 정확해집니다. 머신에 있어서 '경험'은 '이용 가능한 입력 데이터의 양'입니다. 비지도 학습 모델이 사용되는 대표적인 예는 안면 인식, 유전자 서열 분석, 시장 조사, 사이버 보안 등입니다.

** Clustering +
특정 기준에 따라 유사한 데이터 사례들을 하나의 시작을 여러 하위 군집으로 구분. 일반적으로 전체 데이터 세트를 여러 그룹으로 분류하기 위해 사용하며, 사용자는 고유한 패턴을 찾기 위해 개별 그룹 차원에서 분석을 수행할 수 있음
** 차원 축소 +
고려중인 변수의 개수를 줄이는 작업. 많은 애플리케이션에서 원시 데이터는 아주 높은 차원의 특징을 가지는데, 일부 특징들을 중복되거나 작업과 아무 관련이 없어, 차원 수를 줄이면 관계를 도출하기 쉬워짐.

== Semi-supervized Learning (준지도 학습)

모든 데이터가 시스템에 입력되기 전에 정형화되고 레이블이 지정되어 있다면 더할 나위 없이 완벽할 것입니다. 그러나 실제에서는 이러한 일이 불가능하기 때문에, 대량의 원시 비정형 데이터를 처리해야 하는 경우 준지도 학습은 유효한 해결책이 될 수 있습니다. 이 모델은 소량의 레이블이 지정된 데이터를 입력해 레이블이 없는 데이터 세트를 증강합니다. 이 모델의 핵심은 레이블이 지정된 데이터를 통해 시스템이 학습을 시작하게 하며, 학습 속도와 정확성을 상당한 수준으로 개선하도록 하는 것입니다. 준지도 학습 알고리즘은 레이블이 지정된 데이터를 분석해 레이블이 없는 데이터에 적용 가능한 상관관계가 있는 속성을 찾도록 머신을 학습합니다.

그러나 이 모델에는 이 MIT 대학출판사 보고서에서 자세히 다룬 것과 같이 시스템이 레이블 지정된 데이터에 포함된 결함까지 학습해 복제할 위험이 있습니다. 준지도 학습을 가장 성공적으로 활용하는 회사에서는 선진 사례 프로토콜을 구축하고 있습니다. 준지도 학습은 음성 및 언어 분석, 복잡한 의료 연구(예: 단백질 분류), 상위 레벨 부정 행위 감지에 사용됩니다.

== Reinforcement Learning (강화 학습)

지도형 학습에서는 머신에 정답 키를 제공해 모든 올바른 결과 중에서 상관관계를 찾아 학습하도록 합니다. 강화학습 모델에서는 정답 키는 제공되지 않지만 일련의 허용 가능한 행동, 규칙, 잠재적 최종 상태가 입력됩니다. 알고리즘의 원하는 목표가 고정되어 있거나 양자택일인 경우 머신은 예시를 통해 학습할 수 있습니다. 그러나 원하는 목표가 변동 가능한 경우에는 경험과 보상을 통해 학습해야 합니다. 강화학습 모델에서 '보상'은 숫자이며, 시스템에서 수집하려는 항목으로 알고리즘에 프로그래밍됩니다.

이 모델은 여러 면에서 사람에게 체스 게임을 하는 법을 가르치는 것과 유사합니다. 체스 말이 이동할 수 있는 경우를 모두 보여주는 것은 불가능하며, 그 대신 규칙을 설명해주고 연습을 통해 기술을 습득하도록 합니다. 보상은 게임을 이기는 것뿐 아니라 상대방의 말을 획득하는 형태로 이루어집니다. 강화학습 적용 분야에는 온라인 광고 구매자의 자동 가격 입찰, 컴퓨터 게임 개발, 고위험 주식 시장 거래 등이 있습니다.


