= Lab 5-2 특성 개수와 과대적합

이 연습에서는 특성의 개수에 따른 학습 과대적합을 학습합니다. 아래 절차에 따릅니다.

== 실습 환경 준비

여기에서는 Visual Studio Code의 Jupyter Notebook을 사용하여 연습을 수행합니다. 이 연습의 수행 환경은 Lab 1-1에서와 같습니다.

1. Visual Studio Code를 실행합니다.
2. 파일 메뉴에서 폴더 열기 를 클릭합니다.
3. 연습을 수행할 폴더를 선택하고 확인 버튼을 클릭합니다.
4. Visual Studio Code의 Explorer 에서 New Button을 클릭하여 새 파일을 만들고, 이름을 lab3-1.ipynb로 지정합니다.
5. 오른쪽 위의 Select Kernel 을 클릭하고 Anaconda Python 환경을 선택합니다.
6. + Code 버튼을 클릭하여 노트북을 시작합니다.

== 라이브러리 import

이 연습에서는 Pandas, Numpy, Matplotlib, Scikit Learn 라이브러리를 사용합니다. 아래 절차에 따라 필요한 라이브러리를 import 합니다.

1. 생성한 Code 노트에 아래 코드를 입력합니다.
+
[source, python]
----
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt
----
+
2. Shift + Enter 를 클릭하여 작성한 코드를 실행합니다.

== 데이터 준비

이 연습에서는 농어의 길이와 무게 데이터에 더해, 높이와 두께가 데이터를 추가로 사용합니다. 아래 절차에 따릅니다.

1. https://github.com/gikpreet/class-machine_learning/blob/main/Module%2005%20Feature%20Engineering/data/perch.csv 에서 소스 파일을 다운로드 합니다.
2. 아래와 유사한 코드를 실행하여 데이터를 DataFrame으로 로드하고 데이터를 확인합니다.
+
[source, python]
----
df = pd.read_csv('../data/perch.csv')
df.head()
----
+
[%header, cols="1,2,2,2" width=50%]
|===
||	length|	height|	width
|0|	8.4|	2.11|	1.41
|1|	13.7|	3.53|	2.00
|2|	15.0|	3.82|	2.43
|3|	16.2|	4.59|	2.63
|4|	17.4|	4.59|	2.94
|===

3. 다음 코드를 실행하여 데이터 프레임을 numpy 배열로 변환하고, 데이터를 확인합니다.
+
[source, python]
----
perch_full = df.to_numpy()
print(perch_full)
----
+
4. Target 데이터는 이전의 데이터를 그대로 사용합니다. 아래 코드를 실행합니다.
+
[source, python]
----
perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])
----
+
5. 아래 코드를 실행하여 학습 세트와 테스트 세트를 나눕니다.
+
[source, python]
----
train_input, test_input, train_target, test_target = train_test_split(perch_full, perch_weight, random_state=42)
----

== 특성 추가

여기에서는 차원을 5개로 설정하여 특성의 개수를 늘입니다. 아래 절차에 따릅니다.

1. 아래 코드를 실행하여 5차원 특성을 만듭니다. 
+
[source, python]
----
poly = PolynomialFeatures(degree=5, include_bias=False)
poly.fit(train_input)
----
+
2. 생성한 특성을 이용하여 학습 세트와 테스트 세트를 생성합니다.
+
[source, python]
----
train_poly = poly.transform(train_input)
test_poly = poly.transform(test_input)
----

== 모델 생성 후 학습

여기에서는 특성이 추가된 학습 세트와 테스트 세트를 선형 회귀 모델을 사용하여 학습하고 평가합니다. 아래 절차에 따릅니다.

1. 아래 코드를 실행하여 Scikit Learn 선형 회귀 모델 객체를 생성합니다.
+
[source, python]
----
lr = LinearRegression()
----
+
2. 아래 코드를 실행하여 특성이 추가된 학습 세트로 학습을 실행합니다.
+
[source, python]
----
lr.fit(train_poly, train_target)
----
+
3. 아래 코드를 실행하여 학습 세트로 모델을 평가합니다.
+
[source, python]
----
lr.score(train_poly, train_target)
----
+
----
0.9999999999938143
----
+
4. 아래 코드를 실행하여 테스트 세트로 모델을 평가합니다.
+
[source, python]
----
lr.score(test_poly, test_target)
----
+
----
-144.40744532797535
----