= 회귀 분석 개요

* 산점도에 있는 직선을 찾아 데이터를 예측하는 분석 기법
** 관찰된 연속형 변수들에 대해 두 변수 사이의 모형을 구한 뒤 적합도를 측정
** 시간에 따라 변화하는 데이터나 어떤 영향, 가설적 실험, 인과 관계의 모델링등의 통계적 예측에 이용됨
* 변수들간의 함수적 관계를 탐색하여, 독립변수와 종속변수간의 영향을 파악
* 두 연속되는 변수간의 1차적 '선형' 관계로 표현됨

---

회귀(regress)의 원래 의미는 옛 상태로 돌아간다는 것을 의미합니다. 유전학자 프랜시스 골턴은 부모의 키와 아이들의 키 사이의 연관 관계를 연구하면서 부모와 자녀의 키 사이에는 선형적인 관계가 있고 키가 커지거나 작아지는 것 보다는 전체 키 평균으로 돌아가려는 경향이 있다는 가설을 세웠으며 이를 분석하는 방법을 회귀 분석(Regression Analysis)라고 정의했습니다. 

이후 칼 피어슨은 아버지와 아들의 키를 조사한 결과를 바탕으로 함수 관계를 도출하여 회귀 분석 이론을 수학적으로 정립하였습니다.

회귀에서, 변수는 독립변수와 종속변수 두 가지로 나누어 볼 수 있습니다. 독립변수는 결과에 미치는 원인이라고 할 수 있습니다. '여름에는 아이스크림을 많이 먹는다'는 명제가 있으면, 아이스크림 판매량에 영향을 미치는 요인은 여름이됩니다. 기온이 올라가면 아이스크림을 많이 먹는다로 치환하면, '기온'이 독립변수가 되고 '판매량'은 종속변수가 됩니다. 특정 지역에서 여름철 한 달동안 기온에 따른 판매량을 측정해보면 한 달 동안 기온이 높았던 날에 아이스크림이 많이 팔리는 것을 볼 수 있습니다. 이렇게 원인과 결과가 서로 연속되는 개념으로 이해하는 것을 '회귀분석'이라고 합니다. 회귀라는 단어는 '평균으로 돌아간다'는 의미에서 사용되며, 회귀 분석은 일정한 평균을 예측 결과로 도출하게 됩니다.

현대에 와서는 회귀라는 의미는 거의 사라졌습니다. 최근에는 독립 변수와 종속 변수를 설정하고 이들의 관계를 통계적으로 살펴보는 대부분의 방법론을 회귀 분석이라 부릅니다. 시계열 데이터 분석에 회귀 분석 기법이 많이 사용됩니다.

== 다중 회귀 분석(multiple regression analysis)

다중 회귀 분석(multiple regression analysis)은 통계학에서 설명 변수(독립변수)가 2개 이상인 회귀 분석을 말합니다. 2개 이상의 독립변수와 1개의 종속변수의 관계를 분석하는 방법으로, 간격척도 및 비율척도의 연속형 자료로 분석합니다. 

다중 회귀 분석의 목적은, 이미 알려진 수 개의 독립변수를 사용하여 단일의 종속변수를 예측하기 위한 모델을 도출하는 것입니다. 이를 위해 독립변수와 종속변수 사이의 연관성을 반영하는 가장 적합한 선 또는 곡선을 식별합니다. 

독립변수가 1개인 회귀 분석은 단순회귀 분석이라고 합니다.

_𝑦 = 𝛽~0~ + 𝛽~1~𝑥~1~ + 𝛽~2~𝑥~2~ + ⋯ + 𝛽~𝑛~𝑥~𝑛~ + 𝜖_

* 독립 변수(𝑥~1~,𝑥~2~,…,𝑥~𝑛~)와 종속 변수(𝑦)의 관계가 선형이라고 가정합니다.
* 독립 변수의 개수는 여러 개일 수 있습니다.

**목적**
여러 변수의 영향력을 동시에 고려해 종속 변수를 설명하거나 예측합니다.

**특징**
* 독립 변수 간의 상호작용은 분석하지 않습니다.
* 변수 간의 관계는 선형적이어야 합니다.

**예시**
* 광고비(𝑥~1~)와 매장 수(𝑥~2~)가 매출(𝑦)에 미치는 영향.
* 혈압, 체중, 나이가 심혈관 질환 발생에 미치는 영향.

== 다항 회귀 분석(Polynomal Regression Analysis)

다항 회귀 분석은 독립 변수와 종속 변수 간의 비선형 관계를 모델링합니다.

_y = β~0~ + β~1~​x+β~2~x^2^ + β~3~x^3^ + ⋯ +β~n~x^n^ + ϵ_

* 독립 변수는 하나지만, 그 변수의 **다항식(제곱, 세제곱 등)**을 사용합니다.
* 다항식의 차수(degree)를 높여 더 복잡한 비선형 관계를 설명합니다.

**목적**
종속 변수와 독립 변수 간의 곡선 형태의 비선형 관계를 모델링합니다.

**특징**
* 독립 변수는 기본적으로 하나이지만, 이를 제곱, 세제곱 등으로 변형해 다항식으로 확장합니다.
* 독립 변수와 종속 변수 간의 곡선 형태의 관계를 설명.

**예시**
* 시간(𝑥)에 따른 자동차 속도(𝑦)의 변화가 곡선으로 나타나는 경우.
* 온도(𝑥)와 전력 소비량(𝑦) 간의 곡선 관계.

== 다중 회귀 분석과 다항 회귀 분석의 차이

[%header, cols="1,2,2"]
|===
|구분|다중 회귀 분석|다항 회귀 분석
|독립 변수 수|여러 개|보통 한 개 (다항식으로 변형)
|종속-독립 관계|선형 관계|비선형 관계
|수식 구조|𝛽~1~𝑥~1~ + 𝛽~2~𝑥~2~ + ⋯ |𝛽1𝑥 + 𝛽2𝑥 + ⋯
|적용 사례|여러 변수의 영향을 동시에 분석|곡선 형태의 관계 분석
|===

////
https://brunch.co.kr/@minnation/3388
////