= 회귀 분석 개요

* 산점도에 있는 직선을 찾아 데이터를 예측하는 분석 기법
** 관찰된 연속형 변수들에 대해 두 변수 사이의 모형을 구한 뒤 적합도를 측정
** 시간에 따라 변화하는 데이터나 어떤 영향, 가설적 실험, 인과 관계의 모델링등의 통계적 예측에 이용됨
* 변수들간의 함수적 관계를 탐색하여, 독립변수와 종속변수간의 영향을 파악
* 두 연속되는 변수간의 1차적 '선형' 관계로 표현됨

---

회귀(regress)의 원래 의미는 옛 상태로 돌아간다는 것을 의미합니다. 유전학자 프랜시스 골턴은 부모의 키와 아이들의 키 사이의 연관 관계를 연구하면서 부모와 자녀의 키 사이에는 선형적인 관계가 있고 키가 커지거나 작아지는 것 보다는 전체 키 평균으로 돌아가려는 경향이 있다는 가설을 세웠으며 이를 분석하는 방법을 회귀 분석(Regression Analysis)라고 정의했습니다. 

이후 칼 피어슨은 아버지와 아들의 키를 조사한 결과를 바탕으로 함수 관계를 도출하여 회귀 분석 이론을 수학적으로 정립하였습니다.

회귀에서, 변수는 독립변수와 종속변수 두 가지로 나누어 볼 수 있습니다. 독립변수는 결과에 미치는 원인이라고 할 수 있습니다. '여름에는 아이스크림을 많이 먹는다'는 명제가 있으면, 아이스크림 판매량에 영향을 미치는 요인은 여름이됩니다. 기온이 올라가면 아이스크림을 많이 먹는다로 치환하면, '기온'이 독립변수가 되고 '판매량'은 종속변수가 됩니다. 특정 지역에서 여름철 한 달동안 기온에 따른 판매량을 측정해보면 한 달 동안 기온이 높았던 날에 아이스크림이 많이 팔리는 것을 볼 수 있습니다. 이렇게 원인과 결과가 서로 연속되는 개념으로 이해하는 것을 '회귀분석'이라고 합니다. 회귀라는 단어는 '평균으로 돌아간다'는 의미에서 사용되며, 회귀 분석은 일정한 평균을 예측 결과로 도출하게 됩니다.

현대에 와서는 회귀라는 의미는 거의 사라졌습니다. 최근에는 독립 변수와 종속 변수를 설정하고 이들의 관계를 통계적으로 살펴보는 대부분의 방법론을 회귀 분석이라 부릅니다. 시계열 데이터 분석에 회귀 분석 기법이 많이 사용됩니다.



== 다중 회귀 분석

아이스크림 판매량을 단순히 기온으로만 보기에는 어렵습니다. 온도는 같지만 다른 판매량을 보이는 두 지역이 있다면, '가격'과 같은 다른 요소들을 독립변수에 포함시켜야 합니다. '가격'과 '기온'이 독립변수가 되고 '판매량'은 종속변수가 됩니다. 이렇게 원인이 2가지 이상이 되는, 다중 독립변수가 포함되는 회귀 분석을 다중 회귀 분석이라고 합니다.

////
https://brunch.co.kr/@minnation/3388
////