= 훈련 세트와 테스트 세트

* 머신 러닝에서 일반적인 작업은 데이터로부터 학습하고 데이터를 예측할 수 있는 알고리즘을 구축하는 것
** 입력 데이터로부터 수학적 모델을 구축
** 구축된 모델을 이용하여 데이터 기반 예측 또는 결정을 내리는 방식으로 작동
* 입력 데이터는 여러 데이터 세트로 나뉨
** 모델 생성의 단계에서 `훈련`, `검증`, `테스트` 세트 등 세 가지 데이터 세트가 일반적으로 사용됨

---

머신 러닝에서 일반적인 작업은 데이터로 부터 학습하고 데이터를 예측할 수 있는 알고리즘을 연구하고 구축하는 것입니다. 이런 알고리즘은 입력 데이터로부터 수학적 모델을 구축하여 데이터 기반 예측 또는 결정을 내리는 방식으로 작동합니다. 모델을 구축하는데 사용되는 이런 입력 데이터를 여러 데이터 세트로 나뉩니다. 특히 모델 생성의 여러 단계에서 훈련, 검증, 테스트 세트라는 세 가지 데이터 세트가 일반적으로 사용됩니다.

== 훈련 데이터 세트(Training dataset)

모델은 초기에 모델의 매개변수에 맞춰집니다. 모델은 지도 학습 방법을 사용하여 훈련 데이터 스트에 대해 훈련됩니다. 실제로 훈련 데이터 세트는 입력 벡터(또는 스칼라)와 해당 출력 벡터(또는 스칼라)의 쌍으로 구성되는 경우가 많으며, 여기서 답은 일반적으로 목표(또는 Label)로 표시됩니다. 현재 모델은 훈련 데이터 세트를 사용하여 실행되고 결과를 생성한 다음 훈련 데이터 세트의 각 입력 벡터에 대해 목표와 비교됩니다.

학습 데이터 세트는 학습 과정에서 사용되는 예제의 데이터 세트이며 분류기 등의 매개변수(예: 가중치)를 맞추는 데 사용됩니다.

분류 작업의 경우 지도 학습 알고리즘은 훈련 데이터 세트를 살펴보고 좋은 예측 모델링을 생성할 변수의 최적 조합을 결정하거나 학습합니다. 목표는 알려지지 않은 새로운 데이터에 잘 일반화되는 훈련된(적합된) 모델을 생성하는 것이다. 적합 모델은 보유 데이터 세트(검증 및 테스트 데이터 세트)의 "새로운" 예시를 사용하여 평가되어 새 데이터를 분류할 때 모델의 정확도를 추정한다. 과적합과 같은 문제의 위험을 줄이려면 검증 및 테스트 데이터 세트의 예를 사용하여 모델을 훈련해서는 안 됩니다.

== 검증 데이터 세트(Validation dataset)

그 다음 단계로, 적합 모델은 검증 데이터 세트라는 두 번째 데이터 세트의 관측값에 대한 반응을 예측하는데 사용됩니다. 검증 데이터 세트는 모델의 파라미터를 조정하는 동시에 훈련 데이터 세트에 맞는 모델에 대한 편견 없는 평가를 제공합니다. 검증 데이터 세트는 조기 중단을 통해 정규화에 사용될 수 있습니다. 

검증 데이터 세트는 분류기의 하이퍼파라미터를 조정하는 데 사용되는 예제 데이터 세트이며, 개발 세트 라고도 불립니다. 테스트 세트와 마찬가지로 훈련 데이터 세트와 동일한 확률 분포를 따라야 합니다.

과적합을 방지하기 위해 분류 매개변수를 조정해야 하는 경우 훈련 및 테스트 데이터 세트 외에 검증 데이터 세트가 필요합니다. 예를 들어 문제에 가장 적합한 분류기를 찾는 경우 훈련 데이터 세트를 사용하여 다양한 후보 분류기를 훈련하고 검증 데이터 세트를 사용하여 성능을 비교하고 어떤 분류기를 선택할지 결정한 다음 마지막으로 테스트 데이터를 결정합니다. 세트는 정확도, 민감도, 특이성, F-측정값 등과 같은 성능 특성을 얻는 데 사용된다. 검증 데이터 세트는 하이브리드로 작동합니다. 즉, 테스트에 사용되는 훈련 데이터이지만 하위 수준 훈련의 일부나 최종 테스트의 일부로는 사용되지 않습니다.

모델 선택을 위해 검증 데이터 세트를 사용하는 기본 프로세스(훈련 데이터 세트, 검증 데이터 세트 및 테스트 데이터 세트의 일부)는 다음과 같습니다.

> 목표는 새로운 데이터에서 가장 우수한 성능을 보이는 네트워크를 찾는 것이므로, 다양한 네트워크를 비교하는 가장 간단한 접근 방식은 훈련에 사용된 데이터와 독립적인 데이터를 사용하여 오차 함수를 평가하는 것이다. 훈련 데이터 세트에 대해 정의된 적절한 오차 함수를 최소화하여 다양한 네트워크를 훈련한다. 그런 다음 독립적인 검증 집합을 사용하여 오차 함수를 평가하여 네트워크의 성능을 비교하고, 검증 집합에 대해 오차가 가장 작은 네트워크를 선택한다. 이 접근 방식을 '홀드 아웃' 방법이라고 한다. 이 절차는 그 자체로 검증 집합에 대한 과적합을 초래할 수 있으므로, 선택된 네트워크의 성능은 테스트 집합이라고 하는 세 번째 독립적인 데이터 집합에서 성능을 측정하여 확인해야 한다.

1. 여러 모델을 각각 훈련 데이터셋으로 학습시킨다.
2. 각 모델의 성능을 검증 데이터셋으로 평가한다.
3. 가장 좋은 결과를 보인 모델을 선택한다.
4. 선택된 모델의 최종 성능을 테스트 데이터셋으로 평가한다.

이 프로세스의 적용은 후보 모델이 동일한 네트워크의 연속 반복이고 검증 세트의 오류가 커지면 훈련을 중지하고 이전 모델(오류가 최소인 모델)을 선택하는 조기 중단 과정에 있습니다.

이 과정의 한 가지 응용은 조기 종료(early stopping)에서 볼 수 있다. 이때 후보 모델들은 동일한 네트워크의 연속적인 반복이며, 검증 세트에서의 오류가 증가할 때 학습을 중단하고, 이전 모델(오류가 최소인 모델)을 선택합니다.

== 테스트 데이터 세트(Test dataset)

훈련 데이터 세트에 맞는 최종 모델에 대한 편견없는 평가를 제공하는데 사용되는 데이터 세트입니다. 테스트 데이터 세트의 데이터가 훈련에 사용된 적이 없는 경우 테스트 데이터 세트를 홀드아웃 데이터 세트라고 부르기도 합니다.

테스트 데이터 세트는 훈련 데이터 세트와 확률론적 의미에서의 독립이지만 훈련 데이터 세트와 동일한 확률 분포를 따르는 데이터 세트입니다. 훈련 데이터 세트에 맞는 모델이 테스트 데이터 세트에도 잘 맞는 경우 과적합이 최소화된 것입니다(아래 그림 참조). 테스트 데이터 세트와 달리 훈련 데이터 세트를 더 잘 맞추는 것은 일반적으로 과적합을 가리킵니다.

따라서 테스트 세트는 완전히 지정된 분류기의 성능(즉, 일반화)을 평가하는 데에만 사용되는 예제 세트입니다. 이를 위해 최종 모델은 테스트 세트의 예제 분류를 예측하는 데 사용되며, 이러한 예측은 모델의 정확도를 평가하기 위해 예제의 실제 분류와 비교됩니다.

검증 데이터 세트와 테스트 데이터 세트가 모두 사용되는 시나리오에서 테스트 데이터 세트는 일반적으로 검증 프로세스 중에 선택된 최종 모델을 평가하는 데 사용됩니다. 원본 데이터 세트가 두 개의 하위 세트(훈련 및 테스트 데이터 세트)로 분할된 경우 테스트 데이터 세트는 모델을 한 번만 평가할 수 있습니다(예: 홀드아웃 방법 에서). 이러한 방법을 권장하지 않는 경우도 있으나, 교차 검증 과 같은 방법을 사용하는 경우 편향과 가변성을 줄이는 데 도움이 되도록 모델 학습 및 테스트를 반복한 후 결과를 평균화하므로 두 개의 파티션으로 충분하고 효과적일 수도 있습니다.

////
테스트
https://yhyun225.tistory.com/16
////