= 샘플링 편향(Sampling bias)

* 표본을 잘못 선택함으로써 통계 분석이 왜곡되는 현상
* 모집단의 특정 개인이나 그룹이 다른 개인이나 그룹토다 표본에 포함될 가능성이 높아 대표성을 갖지 못하는 상황
** 비 무작위 샘플링 방법 사용
** 자기 선택 편향적 선택
** 연구자 편향적 선택

---

표준 추출 편향이라 부르기도 하는 샘플링 편향은 모집단의 특정 개인이나 그룹이 다른 개인이나 그룹보다 표존에 포함될 가능성이 높아 표본이 편향되거나 대표성을 갖지 못ㄱ하는 상황을 말합니다. 이는 비무작위 샘플링 방법, 자기 선택 편향, 연구자 편형 등 다양한 이유로 발생할 수 있습니다.

즉, 표본 편향은 전체 모집단을 대표하지 않을 수 있는 특성이나 관점에 유리하도록 표본을 왜곡하여 연구 결과의 타당성과 일반화 가능성을 저해할 수 있습니다.

설문조사를 수행할 경우, 모든 설문조사 참가자를 무작위로 선택하는 것이 가장 이상적입니다. 그러나 실제로는 비용 및 응답자 가용성 등의 제약으로 인해 무작위로 참가자를 선정하는 것이 어려울 수 있습니다. 무작위 데이터 수집을 하지 않더라도 데이터에 존재할 수 있는 잠재적인 편향성을 인식하는 것이 중요합니다.

== 샘플링 편향의 예

* **자원 봉사자 편향성** +
연구에 자원하여 참여한 참가자는 자원하지 않은 참가자와 다른 특성을 가질 수 있으므로 대표성이 없는 표본이 될 수 있습니다.
* **비무작위 샘플링** +
연구자가 특정 지역에서만 참가자를 선택하거나 특정 특성을 가진 참가자만 선택하면 편향된 표본이 될 수 있습니다.
* **생존자 편향** +
특정 상황에서 생존하거나 성공한 사람만 표본에 포함되고 생존하지 못했거나 실패한 사람은 제외되는 경우 발생합니다.
* **편리한 샘플링** +
이 유형의 샘플링에는 주변에 있는 사람이나 온라인 설문조사에 응답하는 사람 등 쉽게 접근할 수 있는 참가자를 선택하는 것이 포함되며, 이는 전체 인구를 대표하지 않을 수 있습니다.
* **확증 편향** +
연구자는 무의식적으로 또는 의도적으로 자신의 가설이나 연구 질문을 지지하는 참가자를 선택해 편향된 결과를 초래할 수 있습니다.
* **호손 효과** +
참여자는 자신이 연구 또는 관찰되고 있다는 사실을 알면 행동이나 응답을 변경하여 대표성이 없는 결과를 초래할 수 있습니다.

== 샘플링 편향의 유형

* **선택 편향** +
샘플이 모집단을 대표하지 않을 때 발생합니다.
* **측정 편향** +
수집된 데이터가 부정확하거나 불완전한 경우 발생합니다.
* **편향성 보고** +
응답자가 부정확하거나 불완전한 정보를 제공할 때 발생합니다.
* **무응답 편향** +
모집단의 일부 구성원이 설문 조사에 응답하지 않아 대표성이 없는 표본이 될 때 발생합니다.

== 샘플링 편향의 원인

* **편리한 샘플링** +
과학적 방법이 아닌 편의에 따라 샘플을 선택함.
* **자기 선택 편향설** +
설문조사에 자발적으로 참여한 사람만 포함되며, 전체 인구를 대표하지 않을 수 있습니다.
* **샘플링 프레임 바이어스** +
표본을 선택하는 데 사용된 샘플링 프레임이 모집단을 대표하지 않는 경우입니다.
* **생존 편향** +
인구의 특정 구성원만 참여하여 대표성이 없는 표본이 되는 경우입니다. 예를 들어, 연구자가 살아있는 사람만을 대상으로 설문조사를 실시할 경우, 연구가 진행되기 전에 사망한 사람의 의견을 받지 못할 수 있습니다.
* **지식 부족으로 인한 샘플링 편향** +
편향된 추정치를 초래할 수 있는 변동성의 원인을 인식하지 못합니다.
* **샘플 관리 오류로 인한 샘플링 편향성** +
적절하거나 잘 작동하는 샘플링 프레임을 사용하지 않거나 연구 참여를 거부하여 샘플이 편향적으로 선택되는 경우.

== 샘플링 편향으로 인한 문제

표본 편향이 문제가 되는 이유는 표본으로 계산된 통계가 체계적으로 오류를 일으킬 수 있기 때문입니다. 이는 모집단에서 해당 매개변수를 체계적으로 과대 또는 과소 추정하는 결과를 초래할 수 있습니다. 샘플링에서 완벽한 무작위성을 보장하는 것은 사실상 불가능하기 때문에 실제로 편향이 발생합니다.

허위 진술의 정도가 작다면 해당 샘플은 무작위 샘플에 대한 합리적인 근사치로 취급할 수 있습니다. 또한 샘플의 측정 수량이 현저하게 다르지 않다면 편향된 샘플도 합리적인 추정치가 될 수 있습니다.

일부 개인이 의도적으로 편향된 표본을 사용하여 잘못된 결과를 도출할 수도 있지만, 편향된 표본은 진정한 대표성을 지닌 표본을 확보하기 어렵거나 측정 또는 분석 과정에서 편향성에 대한 무지의 반영일 뿐인 경우가 더 많습니다.

== 샘플링 편향성 완화를 위한 모범 사례

결과 데이터가 연구 대상 집단을 정확하게 반영할 수 있도록 적절한 샘플링 방법을 선택하는 것이 중요합니다.

* **무작위 샘플링 기법** +
무작위 샘플링 기법을 사용하면 표본이 모집단을 대표할 확률이 높아집니다. 이 기법을 사용하면 표본이 해당 모집단을 최대한 대표할 수 있으므로 편향이 포함될 가능성이 줄어듭니다.
* **샘플 크기 계산** +
통계적으로 의미 있는 가설을 테스트할 수 있는 적절한 검정력을 확보할 수 있도록 표본 크기를 계산해야 합니다. 표본 크기가 클수록 모집단을 더 잘 대표할 수 있습니다.
* **트렌드 분석** +
대체 데이터 소스를 찾고 선택되지 않았을 수 있는 데이터에서 관찰된 추세를 분석합니다.
* **편향성 확인** +
특정 데이터 포인트가 체계적으로 제외되거나 과도하게 포함되는 것을 식별하기 위해 편향의 발생을 모니터링해야 합니다.

샘플링 편향은 연구를 수행할 때 중요한 고려 사항입니다. 사용된 방법론이나 연구 분야에 관계없이 연구자는 연구 대상 인구의 특성을 반영하는 대표적인 표본을 사용하고 있는지 확인해야 합니다.

연구 조사를 작성할 때는 표본 선정 과정과 표본에서 데이터를 수집하는 데 사용되는 방법론에 세심한 주의를 기울이는 것이 중요합니다. 무작위 표본 추출 기법, 표본 크기 계산, 추세 분석, 편향성 확인과 같은 모범 사례를 사용하여 연구 결과가 타당하고 신뢰할 수 있는지 확인해야 정책과 실무에 영향을 미칠 가능성이 높아집니다.

////
https://mindthegraph.com/blog/ko/%EC%83%98%ED%94%8C%EB%A7%81-%ED%8E%B8%ED%96%A5/
////