= Numpy

* Python에서 과학 연산을 위한 가장 기본적인 패키지 중의 하나
* 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수와 메소드를 제공
* 데이터 분석, 데이터 처리, 선형 대수, 머신 러닝 등 다양한 분야에서 널리 사용됨

---

Numpy는 Python에서 과학 연산을 위한 가장 기본적인 패키지중의 하나입니다. Python의 List로 2차원 리스트를 표현할 수 있지만 다차원 List를 만드려면 번거로운 작업들을 해야합니다. Numpy를 사용하면 다차원 배열을 쉽게 만들고 조작할 수 있습니다. Numpy는 "Numeric Python"의 약자이며 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수와 메소드를 제공합니다. Numpy는 데이터 분석, 데이터 처리, 선형 대수, 머신 러닝 등 다양한 분야에서 널리 사용됩니다.

== Numpy 배열 생성

Numpy 배열은 동일한 타입의 데이터를 저장하는 다차원 배열입니다. Numpy 배열은 ndarray 클래스이며, 아래와 같이 생성할 수 있습니다.

[source, python]
----
import numpy as np

# 1차원 배열
array = np.array([1,2,3])

# 2차원 배열
matrix = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

# 3차원 배열
cube = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [7,8,9],
            [10,11,12]
        ]
    ]
)
----

Numpy가 지원하는 함수를 사용하여 다양한 형태의 배열을 생성할 수 있습니다. 배열을 생성하는 주요 함수들은 아래와 같습니다.

[%header, cols="1,4"]
|===
|함수|설명
|zeros()|모든 원소가 0인 배열을 생성합니다
|np.ones()| 모든 원소가 1인 배열을 생성합니다.
|np.arange()| 범위 내의 일정 간격을 가진 배열을 생성합니다.
|np.linspace()| 범위 내에서 균등 간격으로 원하는 개수의 배열을 생성합니다.
|np.random.random()|0부터 1사이의 난수를 가지는 배열을 생성합니다.
|np.random.randn()|평균이 0이고 표준편차가 1인 정규 분포를 따르는 난수를 가지는 배열을 생성합니다.
|===

=== zeros() 함수

np.zeros() 함수는 모든 원소가 0인 배열을 생성합니다. 함수의 인수로는 생성할 배열의 크기를 지정합니다. 예를 들어, 크기가 2x3인 배열을 생성하려면 다음과 같이 코드를 작성합니다.

[source, python]
----
import numpy as np

arr = np.zeros((2, 3))
print(arr)
----

----
[[0. 0. 0.]
 [0. 0. 0.]]
----

=== ones() 함수

np.ones() 함수는 모든 원소가 1인 배열을 생성합니다. 함수의 인수로는 생성할 배열의 크기를 지정합니다. 예를 들어, 크기가 2x4인 배열을 생성하려면 다음과 같이 코드를 작성합니다.

[source, python]
----
import numpy as np

arr = np.ones((2, 4))
print(arr)
----

----
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----

=== arrange() 함수

np.arange() 함수는 범위 내의 일정 간격을 가진 배열을 생성합니다. 함수의 인수로는 생성할 배열의 범위와 간격을 지정합니다. 예를 들어, 범위가 1에서 10까지이고 간격이 2인 배열을 생성하려면 다음과 같이 코드를 작성합니다.

[source, python]
----
import numpy as np

arr = np.arange(1, 10, 2)
print(arr)
----

----
[1 3 5 7 9]
----

=== linspace() 함수

np.linspace() 함수는 범위 내에서 균등 간격으로 원하는 개수의 배열을 생성합니다. 함수의 인수로는 생성할 배열의 범위와 원하는 개수를 지정합니다. 예를 들어, 범위가 0에서 1까지이고 원하는 개수가 5개인 배열을 생성하려면 다음과 같이 코드를 작성합니다.

[source, python]
----
import numpy as np

arr = np.linspace(0, 1, 5)
print(arr)
----

----
[0.   0.25 0.5  0.75 1.  ]
----

=== random.random() 함수

np.random.random() 함수는 0과 1사이의 균등 분포에서 난수를 생성하여 배열을 만듭니다. 함수의 인수로는 생성할 배열의 크기를 지정할 수 있습니다. 예를 들어, 크기가 3x3인 배열을 생성하려면 다음과 같이 코드를 작성합니다.

[source, python]
----
import numpy as np

arr = np.random.random((3, 3))
print(arr)
----

----
[[0.8139928  0.79544491 0.43146849]
 [0.30136094 0.77515306 0.64259144]
 [0.02956163 0.74888294 0.56169272]]
----

=== random.randn() 함수

np.random.randn() 함수는 평균이 0이고 표준편차가 1인 정규 분포를 따르는 난수를 생성하여 배열을 만듭니다. 함수의 인수로는 생성할 배열의 크기를 지정할 수 있습니다. 예를 들어, 크기가 2x4인 배열을 생성하려면 다음과 같이 코드를 작성합니다.

[source, python]
----
import numpy as np

arr = np.random.randn(2, 4)
print(arr)
----

----
[[ 0.52346546  0.30785207  0.63301317 -0.03108197]
 [ 1.37352221 -1.26632616 -1.15567608 -0.52687134]]
----

== Numpy 배열 연산

Numpy 배열은 다른 배열 또는 스칼라와의 연산을 지원합니다. 

[source, python]
----
array = np.array([1,2,3])
array2 = array + 1
print(array2)
----

----
[2,3,4]
----

[source, python]
----
matrix = np.array([[1,2,3],[4,5,6]])
matrix2 = matrix + 1
----

----
[[2 3 4]
 [5 6 7]]
----

배열간의 연산도 수행할 수 있습니다.

[source, python]
----
array3 = array2 + array
print(array3)
----

----
[3 5 7]
----

[source, python]
----
matrix3 = matrix2 * matrix
print(matrix3)
----

----
[[ 2  6 12]
 [20 30 42]]
----

== 인덱싱과 슬라이싱

List와 유사한 방법으로 인덱싱, 슬라이싱을 사용하여 배열의 일부를 선택할 수 있습니다.

[source, python]
----
a = np.array([1, 2, 3, 4, 5])

# 인덱싱
b = a[0]  # 1
c = a[2]  # 3

# 슬라이싱
d = a[1:4]  # [2, 3, 4]
e = a[:3]   # [1, 2, 3]
f = a[3:]   # [4, 5]
----

다차원 NumPy 배열에서는 각 차원의 인덱스를 콤마로 구분하여 인덱싱할 수 있습니다.

[source, python]
----
a = np.array([[1, 2, 3], [4, 5, 6]])

# 인덱싱
b = a[0, 0]  # 1
c = a[1, 2]  # 6

# 슬라이싱
d = a[0, 1:3]  # [2, 3]
e = a[:, 1]    # [2, 5]
f = a[:, :2]   # [[1, 2], [4, 5]]
----

== 병합과 분리

Numpy 배열은 병합과 분리가 가능합니다.

=== 병합

NumPy 배열을 병합하는 방법은 다음과 같습니다.

[source, python]
----
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))  # [1, 2, 3, 4, 5, 6]
----

다차원 NumPy 배열을 병합하는 방법은 concatenate() 함수를 사용합니다. concatenate() 함수는 병합할 배열을 첫 번째 인자로 전달하며, 두 개 이상의 배열을 병합할 경우에는 튜플 형태로 전달합니다. axis 인자를 사용하여 병합할 방향을 지정할 수 있습니다. axis 인자를 지정하지 않을 경우 기본값인 0으로 설정됩니다.

[source, python]
----
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# 배열 병합
c = np.concatenate((a, b), axis=0)  # [[1, 2], [3, 4], [5, 6]]
----

=== 분리

NumPy 배열을 분리하는 방법은 다음과 같습니다.

[source, python]
----
a = np.array([1, 2, 3, 4, 5, 6])

# 배열 분리
b, c = np.split(a, [3])  # [1, 2, 3], [4, 5, 6]
----

다차원 NumPy 배열을 분리하는 방법은 split() 함수를 사용합니다. split() 함수는 분리할 배열과 분리할 인덱스를 전달하며, 분리할 인덱스는 분리될 배열의 첫 번째 차원을 따라 지정합니다. split() 함수는 분리된 배열을 튜플 형태로 반환합니다.

[source, python]
----
a = np.array([[1, 2, 3], [4, 5, 6]])

# 배열 분리
b, c = np.split(a, [1], axis=0)  # [[1, 2, 3]], [[4, 5, 6]]
----

== 수학/통계 함수

Numpy 배열은 수학/통계를 위한 다양한 메소드와 함수를 가지고 있습니다. 주요 메소드와 함수 목록은 다음과 같습니다.

[%header, cols="1,4"]
|===
|함수|설명
|sum()|배열 요소의 전체 값을 구합니다
|mean()|배열 요소의 평균을 구합니다
|cumsum()|배열 요소의 누적 합을 구합니다
|cumprod()|배열 요소의 누적 곱을 구합니다
|std()|배열 요소의 표준편차를 구합니다
|var()|배열 요소의 분산을 구합니다
|min()|배열 요소 중에서 제일 작은 값을 구합니다
|max()|배열 요소중 최대값을 구합니다
|argmin()|최소 원소의 인덱스 값을 구합니다
|argmax()|최대 원소의 인덱스 값을 구합니다
|===

== 난수 함수

NumPy 모듈의 랜덤 함수를 사용하여 다양한 분포에서 난수를 생성할 수 있습니다. 이를 통해 데이터의 모의 실험을 수행하거나 시뮬레이션을 구현할 수 있습니다. numpy.random 모듈의 경우는 다양한 종류의 확률분포로부터 효과적으로 표본 값을 생성하는데 사용됩니다.

[%header, cols="1,4"]
|===
|함수|설명
|seed()|난수 발생기의 seed를 지정합니다
|permutation()|임의의 순열을 반환합니다
|shuffle()|리스트나 배열의 순서를 뒤섞습니다
|rand()|균등분포에서 표본을 추출합니다
|randint()|주어진 최소/최대 범위 안에서 임의의 난수를 추출합니다
|randn()|표준편차가 1이고 평균값이 0인 정규분포에서 표본을 추출합니다
|binomial()|이항분포에서 표본을 추출합니다
|normal()|정규분포(가우시안)에서 표본을 추출합니다
|beta()|베타분포에서 표본을 추출합니다
|chisquare()|카이제곱분포에서 표본을 추출합니다
|gamma()|감마분포에서 표본을 추출합니다
|uniform()|균등(0,1)에서 표본을 추출합니다
|===

////
https://velog.io/@euisuk-chung/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%8B%9C%EA%B0%81%ED%99%94-%EB%A7%88%EC%8A%A4%ED%84%B0%ED%95%98%EA%B8%B0-Numpy
////