= Lab 6-2 로지스틱 회귀를 사용한 분류

이 연습에서는 특정한 경우에 선택될 수 있는 생선의 종류에 대한 확률을 구하는 머신러닝 프로그램을 작성합니다.

== 실습 환경 준비

여기에서는 Visual Studio Code의 Jupyter Notebook을 사용하여 연습을 수행합니다. 이 연습의 수행 환경은 Lab 1-1에서와 같습니다.

. Visual Studio Code를 실행합니다.
. 파일 메뉴에서 폴더 열기 를 클릭합니다.
. 연습을 수행할 폴더를 선택하고 확인 버튼을 클릭합니다.
. Visual Studio Code의 Explorer 에서 New Button을 클릭하여 새 파일을 만들고, 이름을 lab3-1.ipynb로 지정합니다.
. 오른쪽 위의 Select Kernel 을 클릭하고 Anaconda Python 환경을 선택합니다.
. + Code 버튼을 클릭하여 노트북을 시작합니다.

== 라이브러리 import

이 연습에서는 Pandas, Numpy, Matplotlib, Sckit Learn 라이브러리를 사용합니다. 아래 절차에 따라 필요한 라이브러리를 import 합니다.

1. 생성한 Code 노트에 아래 코드를 입력합니다.
+
[source, python]
----
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
----

== 데이터 준비

이 연습에서는 종류, 무게, 길이, 대각선 높이, 두게 등 6개의 특성을 가지는 생선 데이터를 사용합니다. 아래 절차에 따릅니다.

1. https://github.com/gikpreet/class-machine_learning/blob/main/Module%2006%20Prediction_Classification/data/fish.csv 에서 데이터 파일을 다운로드합니다.
2. 아래와 유사한 코드를 실행하여 데이터를 DataFrame으로 로드하고 데이터를 확인합니다.
+
[source, python]
----
df_fish = pd.read_csv('../data/fish.csv')
df_fish.head()
----
+
[%header, cols=7, width=500]
|===
||Species|Weight|Length|Diagonal|Height|Width
|0|Bream|242.0|25.4|30.0|11.5200|4.0200
|1|Bream|290.0|26.3|31.2|12.4800|4.3056
|2|Bream|340.0|26.5|31.1|12.3778|4.6961
|3|Bream|363.0|29.0|33.5|12.7300|4.4555
|4|Bream|430.0|29.0|34.0|12.4440|5.1340
|===
+
3. 아래 코드를 실행하여 생선의 종류를 확인합니다.
+
[source, python]
----
print(pd.unique(df_fish.Species))
----
+
----
['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']
----
+
4. 아래 코드를 실행하여 입력 데이터와 타겟 데이터를 준비합니다.
+
----
fish_input = df_fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = df_fish.Species.to_numpy()
----
+
5. 아래 코드를 실행하여 학습 세트와 테스트 세트를 준비합니다.
+
[source, python]
----
train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, random_state=42)
----

== 정규화

여기서는 StandardScalar 객체를 사용하여 학습 세트와 테스트 세트를 정규화합니다. 아래 절차에 따릅니다.

1. 아래 코드를 실행하여 학습 세트와 테스트 세트를 정규화합니다.
+
[source, python]
----
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)
----

== 이진 분류 데이터 생성

여기서는 numpy 배열의 boolean indexing을 사용하여 학습 타겟 데이터 세트에서 도미(Bream)과 빙어(Smelt) 데이터 만을 골라내어 이진 분류의 대상으로 만듭니다. 아래 절차에 따릅니다.

1. 아래 코드를 실행하여 학습 타겟 데이터 세트에서 도미(Bream)과 빙어(Smelt) 데이터에 대한 불리언 인덱스 배열을 만들고 확인합니다.
+
[source, python]
----
bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')
print(bream_smelt_indexes)
----
+
----
[ True False  True False False False False  True False False False  True
 False False False  True  True False False  True False  True False False
 False  True False False  True False False False False  True False False
  True  True False False False False False  True False False False False
 False  True False  True False False  True False False False  True False
 False False False False False  True False  True False False False False
 False False False False False  True False  True False False  True  True
 False False False  True False False False False False  True False False
 False  True False  True False False  True  True False False False False
 False False False False  True  True False False  True False False]
----
+
2. 아래 코드를 실행하여 정규화된 학습 세트와 학습 타겟 세트에서 도미와 빙어 데이터를 추출합니다.
+
[source, python]
----
train_bream_smelt = train_scaled[bream_smelt_indexes]
target_bream_smelt = train_target[bream_smelt_indexes]
----
+
3. 같은 방법으로, 테스트 세트와 테스트 타겟 세트에 대해서도 이진 분류 데이터를 추출합니다.
+
[source, python]
----
bream_smelt_test_indexes = (test_target == 'Bream') | (test_target == 'Smelt')
test_bream_smelt = test_scaled[bream_smelt_test_indexes]
target_test_bream_smalt = test_target[bream_smelt_test_indexes]
----

== LogisticRegression 모델로 학습 및 평가

여기에서는 Scikit Learn의 LogisticRegression 클래스 객체를 만들고 훈련 세트로 모델을 훈련한 다음 학습 세트와 테스트 세트의 점수를 확인합니다. 아래 절차에 따릅니다.

1. 아래 코드를 실행하여 KNeighborClassifier 객체를 생성합니다.
+
[source, python]
----
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
----
+
2. 아래 코드를 실행하여 학습 세트와 학습 타겟 세트를 사용하여 모델을 학습합니다.
+
[source, python]
----
lr.fit(train_bream_smelt, target_bream_smelt)
----
+
3. 아래 코드를 실행하여 모델을 평가합니다.
+
[source, python]
----
print(lr.score(train_bream_smelt, target_bream_smelt))
print(lr.score(test_bream_smelt, target_test_bream_smalt))
----

----
1.0
1.0
----

== 예측

여기에서는 학습한 로지스틱 회귀 모델로 gkrtmq 데이터를 사용하여 생선을 분류합니다. 아래 절차에 따릅니다.

1. 아래 명령을 수행하여 테스트 데이터의 첫 5개 데이터를 분류합니다.
+
[source, python]
----
print(lr.predict(train_bream_smelt[:5]))
----
+
2. LogisticRegression 모델 역시 KNeighborClassifier 모델 처럼 예측 확률을 볼 수 있는 predict_proba()메소드를 제공합니다. 아래 코드를 실행하여 각 데이터의 분류 확률을 출력합니다.
+
[source, python]
----
print(lr.predict_proba(test_bream_smelt[:5]))
----
+
----
[[0.99760007 0.00239993]
 [0.02737325 0.97262675]
 [0.99486386 0.00513614]
 [0.98585047 0.01414953]
 [0.99767419 0.00232581]]
----
+
3. 아래 코드를 실행하여 양성 클래스와 음성 클래스를 확인합니다.
+
[source, python]
----
print(lr.classes_)
----
+
----
['Bream' 'Smelt']
----