= = Lab 6-2 다중 로지스틱 회귀를 사용한 분류

이 연습에서는 로지스틱 회귀 분류를 확장한 다중 로지스틱 회귀를 사용하여 생선의 종류를 구하는 머신 러닝 프로그램을 작성합니다.

== 실습 환경 준비

여기에서는 Visual Studio Code의 Jupyter Notebook을 사용하여 연습을 수행합니다. 이 연습의 수행 환경은 Lab 1-1에서와 같습니다.

. Visual Studio Code를 실행합니다.
. 파일 메뉴에서 폴더 열기 를 클릭합니다.
. 연습을 수행할 폴더를 선택하고 확인 버튼을 클릭합니다.
. Visual Studio Code의 Explorer 에서 New Button을 클릭하여 새 파일을 만들고, 이름을 lab3-1.ipynb로 지정합니다.
. 오른쪽 위의 Select Kernel 을 클릭하고 Anaconda Python 환경을 선택합니다.
. + Code 버튼을 클릭하여 노트북을 시작합니다.

== 라이브러리 import

이 연습에서는 Pandas, Numpy, Matplotlib, Sckit Learn 라이브러리를 사용합니다. 아래 절차에 따라 필요한 라이브러리를 import 합니다.

. 생성한 Code 노트에 아래 코드를 입력합니다.
+
[source, python]
----
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
----

== 데이터 준비

이 연습에서는 종류, 무게, 길이, 대각선 높이, 두게 등 6개의 특성을 가지는 생선 데이터를 사용합니다. 아래 절차에 따릅니다.

1. https://github.com/gikpreet/class-machine_learning/blob/main/Module%2006%20Prediction_Classification/data/fish.csv 에서 데이터 파일을 다운로드합니다.
2. 아래와 유사한 코드를 실행하여 데이터를 DataFrame으로 로드하고 데이터를 확인합니다.
+
[source, python]
----
df_fish = pd.read_csv('../data/fish.csv')
df_fish.head()
----
+
[%header, cols=7, width=500]
|===
||Species|Weight|Length|Diagonal|Height|Width
|0|Bream|242.0|25.4|30.0|11.5200|4.0200
|1|Bream|290.0|26.3|31.2|12.4800|4.3056
|2|Bream|340.0|26.5|31.1|12.3778|4.6961
|3|Bream|363.0|29.0|33.5|12.7300|4.4555
|4|Bream|430.0|29.0|34.0|12.4440|5.1340
|===
+
3. 아래 코드를 실행하여 생선의 종류를 확인합니다.
+
[source, python]
----
print(pd.unique(df_fish.Species))
----
+
----
['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']
----
+
4. 아래 코드를 실행하여 입력 데이터와 타겟 데이터를 준비합니다.
+
----
fish_input = df_fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = df_fish.Species.to_numpy()
----
+
5. 아래 코드를 실행하여 학습 세트와 테스트 세트를 준비합니다.
+
[source, python]
----
train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, random_state=42)
----

== 정규화

여기서는 StandardScalar 객체를 사용하여 학습 세트와 테스트 세트를 정규화합니다. 아래 절차에 따릅니다.

1. 아래 코드를 실행하여 학습 세트와 테스트 세트를 정규화합니다.
+
[source, python]
----
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)
----

== LogisticRegression 모델로 학습 및 평가

로지스틱 회귀는 기본적으로 반복 알고리즘을 사용합니다. max_iter 파라미터를 통해 반복 횟수를 지정할 수 있으며, 기본 값은 100입니다. 또 로지스틱 회귀는 Ridge 회귀와 같이 L2 규제 방법을 사용하여 계수의 제곱을 규제합니다. 로지스틱 회귀에서는 C 파라미터를 사용하여 규제의 크기를 조정합니다. Rigde 회귀에서는 alpha 값의 크기에 따라 규제가 커졌지만, 로지스틱 회귀에서는 C값이 작아질수록 규제가 커집니다. C의 기본 값은 1입니다.

아래 절차에 따릅니다.

1. 아래 코드를 실행하여 LogisticRegression 객체를 생성합니다.
+
[source, python]
----
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
----
+
2. 아래 코드를 실행하여 모델을 학습합니다.
+
[source, python]
----
lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_scaled, train_target)
----
+
3. 아래 코드를 실행하여 모델을 평가합니다.
+
[source, python]
----
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))
----
+
----
0.9327731092436975
0.925
----

== 분류

여기에서는 테스트 세트의 데이터를 사용하여 데이터를 분류합니다. 아래 절차에 따릅니다.

1. 아래 코드를 실행하여 테스트 세트의 첫 다섯개 데이터를 분류합니다.
+
[source, python]
----
print(lr.predict(test_scaled[:5]))
----
+
----
['Perch' 'Smelt' 'Pike' 'Roach' 'Perch']
----
+
2. 아래 코드를 실행하여 특성별 확률을 확인합니다.
+
[source, python]
----
proba = lr.predict_proba(test_scaled[:5])
print(np.round(proba))
----